sudo: false

language: node_js

node_js:
  - '6'
  - '8'
  - '9'
  - '10'

services:
  - docker

before_install:
  - docker pull opendxl/opendxl-broker
  - docker run -d -p 127.0.0.1:8883:8883 -p 127.0.0.1:8443:8443 opendxl/opendxl-broker
  - docker ps -a

before_script:
  - ./node_modules/.bin/dxlclient provisionconfig -u admin -p password test/integration 127.0.0.1 client
  - sed -i -e "s/127.0.0.1;127.0.0.1/127.0.0.1/g" -e "/local/d" -e "/docker/d" test/integration/dxlclient.config
  - cat test/integration/dxlclient.config

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - npm run ci
